services:
  servicerequestdb:
    image: postgres

  servicerequest.api:
    image: ${DOCKER_REGISTRY-}servicerequestapi
    build:
      context: .
      dockerfile: Services/ServiceRequest/ServiceRequest.API/Dockerfile
      
volumes:
  postgres_servicerequest: